spring:
  application:
    name: gestaodeequipamentos
  data:
    mongodb:
      uri: mongodb+srv://sgee:sgee@clustersgee.i6vorx9.mongodb.net/admin?retryWrites=true&w=majority&appName=ClusterSGEE
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: master3226
    driver-class-name:  com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      #ddl-auto: update
      ddl-auto: none
    properties:
      hibernate.format_sql: true
