spring:
  application:
    name: gestaodeequipamentos

  data:
    mongodb:
      uri: mongodb+srv://teste:teste@clustersgee.i6vorx9.mongodb.net/sgee ?retryWrites=true&w=majority&appName=ClusterSGEE

  datasource:
    url: jdbc:mysql://mysql-3e138b78-testandooooooooooo.l.aivencloud.com:17228/defaultdb
    username: avnadmin
    password: AVNS_0-OpgBW38Ffatt-M0MK
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      #ddl-auto: update
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

